;;; post-early-init.el --- Post Early Init -*- no-byte-compile: t; lexical-binding: t; -*-

;; Obtain the latest packages from MELPA to access new features and
;; improvements. While MELPA packages are generally regarded as less stable,
;; actual breakages are uncommon; over the past year, only a single package
;; (package-lint) out of 146 packages in the minimal-emacs.d author’s
;; configuration experienced a brief disruption, which was quickly resolved.
(setq package-archive-priorities '(("melpa"        . 90)
                                   ("gnu"          . 70)
                                   ("nongnu"       . 60)
                                   ("melpa-stable" . 50)))

;; (setq package-pinned-packages
;;       '((annalist                      . "melpa-stable")
;;         (ansible-doc                   . "melpa-stable")
;;         (apheleia                      . "melpa-stable")
;;         (basic-mode                    . "melpa-stable")
;;         (consult-dir                   . "melpa-stable")
;;         (corfu-prescient               . "melpa-stable")
;;         (dtrt-indent                   . "melpa-stable")
;;         (dumb-jump                     . "melpa-stable")
;;         (elisp-refs                    . "melpa-stable")
;;         (evil-collection               . "melpa-stable")
;;         (f                             . "melpa-stable")
;;         (flymake-quickdef              . "melpa-stable")
;;         (groovy-mode                   . "melpa-stable")
;;         (highlight-defined             . "melpa-stable")
;;         (markdown-toc                  . "melpa-stable")
;;         (org-appear                    . "melpa-stable")
;;         (package-lint-flymake          . "melpa-stable")
;;         (parent-mode                   . "melpa-stable")
;;         (php-mode                      . "melpa-stable")
;;         (prescient                     . "melpa-stable")
;;         (s                             . "melpa-stable")
;;         (tocus                         . "melpa-stable")
;;         (treesit-auto                  . "melpa-stable")
;;         (vertico-prescient             . "melpa-stable")
;;         (visual-fill-column            . "melpa-stable")
;;         (yasnippet-snippets            . "melpa-stable")
;;         (aggressive-indent             . "gnu")
;;         (cape                          . "gnu")
;;         (compat                        . "gnu")
;;         (consult                       . "gnu")
;;         (corfu                         . "gnu")
;;         (csv-mode                      . "gnu")
;;         (dash                          . "gnu")
;;         (diff-hl                       . "gnu")
;;         (diminish                      . "gnu")
;;         (easy-escape                   . "gnu")
;;         (embark                        . "gnu")
;;         (embark-consult                . "gnu")
;;         (expand-region                 . "gnu")
;;         (gcmh                          . "gnu")
;;         (indent-bars                   . "gnu")
;;         (marginalia                    . "gnu")
;;         (modus-themes                  . "gnu")
;;         (orderless                     . "gnu")
;;         (org                           . "gnu")
;;         (rainbow-mode                  . "gnu")
;;         (transient                     . "gnu")
;;         (vertico                       . "gnu")
;;         (yasnippet                     . "gnu")
;;         (ztree                         . "gnu")
;;         (eat                           . "nongnu")
;;         (edit-indirect                 . "nongnu")
;;         (evil-visualstar               . "nongnu")
;;         (exec-path-from-shell          . "nongnu")
;;         (git-modes                     . "nongnu")
;;         (golden-ratio                  . "nongnu")
;;         (goto-chg                      . "nongnu")
;;         (gptel                         . "nongnu")
;;         (lua-mode                      . "nongnu")
;;         (magit                         . "nongnu")
;;         (markdown-mode                 . "nongnu")
;;         (package-lint                  . "nongnu")
;;         (page-break-lines              . "nongnu")
;;         (paredit                       . "nongnu")
;;         (popup                         . "nongnu")
;;         (rainbow-delimiters            . "nongnu")
;;         (undo-fu                       . "nongnu")
;;         (undo-fu-session               . "nongnu")
;;         (wgrep                         . "nongnu")
;;         (with-editor                   . "nongnu")
;;         (ws-butler                     . "nongnu")
;;         (yaml-mode                     . "nongnu")))
